### ISSUE TITLE
Application title missing

### ISSUE THREAD

**Issue by jmtanguy** [kirill-grouchnikov/substance-flamingo#6]
Hello,

Switching from version 7 to 8, the plain ribbon frame is missing the title after the taskbar 
It still looks nice with the new scheme, but having the title back would be great.

Thanks a lot for this project.

```java
SwingUtilities.invokeLater(new Runnable() {
            public void run() {
               JFrame.setDefaultLookAndFeelDecorated(true);
                frame.setTitle("MY TITLE");  // JRibbonFrame
                SubstanceCortex.WindowScope.extendContentIntoTitlePane(frame, SubstanceSlices.HorizontalGravity.TRAILING, SubstanceSlices.VerticalGravity.CENTERED);
                for (final Frame f : Frame.getFrames()) {
                    SwingUtilities.updateComponentTreeUI(f);
                }
                frame.setVisible(true);
            }
        }); 
```

![frame](https://user-images.githubusercontent.com/12199993/39432126-fb344986-4c92-11e8-90d0-7a3d3671a80e.jpg)

**Comment by kirill-grouchnikov** [comment]
Any reason you've added this:

SubstanceCortex.WindowScope.extendContentIntoTitlePane(frame, SubstanceSlices.HorizontalGravity.TRAILING, SubstanceSlices.VerticalGravity.CENTERED);

when you migrated to Substance 8? You can't mix this with the custom title pane layout of the Substance-Flamingo plugin. Otherwise you are declaring that you're taking over the content of the title pane, that would include the title and the contextual tab titles.

**Comment by jmtanguy** [comment]
Yes, switching to V8, the frame title pane does not integrate the application menu, taskbar and contextual tabs for the same code. Wrongly, I figured there could be a new way to do this...

![v8](https://user-images.githubusercontent.com/12199993/39523749-f286ecbe-4e16-11e8-843a-8de75ff585b6.jpg)

![v7](https://user-images.githubusercontent.com/12199993/39523725-dffd9d68-4e16-11e8-9091-c9afd803fa58.jpg)

**Comment by kirill-grouchnikov** [comment]
This is the intended behavior change in version 8, documented at https://github.com/kirill-grouchnikov/substance and https://github.com/kirill-grouchnikov/substance/blob/master/www/release-info/8.0/release-info.md

Before creating your JRibbonFrame, add this call:

        SubstanceCortex.GlobalScope.registerComponentPlugin(new SubstanceFlamingoPlugin());

I've also updated the readme file of Substance-Flamingo plugin with this info.
